// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqPAQoGSU5HQU1FEg8KC1BJTkdfU09D",
            "S0VUEAASDgoKRU5URVJfR0FNRRABEg8KC0NSRUFURV9HQU1FEAISDgoKR0FN",
            "RV9TVEFSVBADEg4KCkxFQVZFX0dBTUUQBBIJCgVTUEFXThAFEgsKB0RFU1BB",
            "V04QBhIICgRNT1ZFEAcSEQoNUExBWUVSX0FDVElPThAIKhYKCkFjdGlvblR5",
            "cGUSCAoESURMRRAAKkUKCE1vdmVUeXBlEg0KCU1PVkVfTk9ORRAAEg0KCU1P",
            "VkVfSURMRRABEg0KCU1PVkVfV0FMSxACEgwKCE1PVkVfUlVOEAMqKAoIVGlt",
            "ZVR5cGUSDQoJQ0hFQ0tfUlRUEAASDQoJU1lOQ19USU1FEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.INGAME), typeof(global::Protocol.ActionType), typeof(global::Protocol.MoveType), typeof(global::Protocol.TimeType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum INGAME {
    [pbr::OriginalName("PING_SOCKET")] PingSocket = 0,
    [pbr::OriginalName("ENTER_GAME")] EnterGame = 1,
    [pbr::OriginalName("CREATE_GAME")] CreateGame = 2,
    [pbr::OriginalName("GAME_START")] GameStart = 3,
    [pbr::OriginalName("LEAVE_GAME")] LeaveGame = 4,
    [pbr::OriginalName("SPAWN")] Spawn = 5,
    [pbr::OriginalName("DESPAWN")] Despawn = 6,
    [pbr::OriginalName("MOVE")] Move = 7,
    [pbr::OriginalName("PLAYER_ACTION")] PlayerAction = 8,
  }

  public enum ActionType {
    [pbr::OriginalName("IDLE")] Idle = 0,
  }

  public enum MoveType {
    [pbr::OriginalName("MOVE_NONE")] MoveNone = 0,
    [pbr::OriginalName("MOVE_IDLE")] MoveIdle = 1,
    [pbr::OriginalName("MOVE_WALK")] MoveWalk = 2,
    [pbr::OriginalName("MOVE_RUN")] MoveRun = 3,
  }

  public enum TimeType {
    [pbr::OriginalName("CHECK_RTT")] CheckRtt = 0,
    [pbr::OriginalName("SYNC_TIME")] SyncTime = 1,
  }

  #endregion

}

#endregion Designer generated code
