// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqSAQoGSU5HQU1FEhIKDkNPTk5FQ1Rf",
            "U09DS0VUEAASDgoKRU5URVJfR0FNRRABEg8KC0NSRUFURV9HQU1FEAISDgoK",
            "R0FNRV9TVEFSVBADEg4KCkxFQVZFX0dBTUUQBBIJCgVTUEFXThAFEgsKB0RF",
            "U1BBV04QBhIICgRNT1ZFEAcSEQoNUExBWUVSX0FDVElPThAIKhYKCkFjdGlv",
            "blR5cGUSCAoESURMRRAAKkUKCE1vdmVUeXBlEg0KCU1PVkVfTk9ORRAAEg0K",
            "CU1PVkVfSURMRRABEg0KCU1PVkVfV0FMSxACEgwKCE1PVkVfUlVOEANiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.INGAME), typeof(global::Protocol.ActionType), typeof(global::Protocol.MoveType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum INGAME {
    [pbr::OriginalName("CONNECT_SOCKET")] ConnectSocket = 0,
    [pbr::OriginalName("ENTER_GAME")] EnterGame = 1,
    [pbr::OriginalName("CREATE_GAME")] CreateGame = 2,
    [pbr::OriginalName("GAME_START")] GameStart = 3,
    [pbr::OriginalName("LEAVE_GAME")] LeaveGame = 4,
    [pbr::OriginalName("SPAWN")] Spawn = 5,
    [pbr::OriginalName("DESPAWN")] Despawn = 6,
    [pbr::OriginalName("MOVE")] Move = 7,
    [pbr::OriginalName("PLAYER_ACTION")] PlayerAction = 8,
  }

  public enum ActionType {
    [pbr::OriginalName("IDLE")] Idle = 0,
  }

  public enum MoveType {
    [pbr::OriginalName("MOVE_NONE")] MoveNone = 0,
    [pbr::OriginalName("MOVE_IDLE")] MoveIdle = 1,
    [pbr::OriginalName("MOVE_WALK")] MoveWalk = 2,
    [pbr::OriginalName("MOVE_RUN")] MoveRun = 3,
  }

  #endregion

}

#endregion Designer generated code
